- name: run on local
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tags: 
    - terraform
  tasks:
    - name: Run terraform
      terraform:
        project_path: ./tf
        state: present
      register: trfrm

    - name: Add host
      add_host: 
        name: "example.org"
        groups: nodes
        ansible_host: 3.124.186.135
        ansible_ssh_private_key_file: ~/cloud-lab/sshkey/server-key.pem
        ansible_user: ubuntu

- hosts: nodes
  name: Update and install packages
  gather_facts: false
  tags: 
    - packages
  become: yes
  tasks:
    - name: Install Jekyll dependencies
      apt:
        name: 
          - ruby
          - build-essential
          - zlib1g-dev
          - wget
        state: present
    - name: Install deploy agent
      command: sh ./script.sh

 

 
